### ISSUE TITLE
testing Almalinux 9 Ansible 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#11]
please test an d confirm is working properly 
if there are problems, please open issues 

https://github.com/dotkernel/development/blob/main/wsl/os/almalinux9/README.md

@OnitaAndrei @SergiuBota1 @Jurj-Bogdan @kakapiciu @AtomicXtreme

**Comment by arhimede** [comment]
@cPintiuta pelase test it too

**Comment by kakapiciu** [comment]
everything went smooth

**Comment by Jurj-Bogdan** [comment]
working as intended

**Comment by SergiuBota1** [comment]
Everythink works fine
