### ISSUE TITLE
strange permission issue

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#12]
/var/www/html folder 

ls -lat return *root* as owner and group 
it supposed to be the WSL  user

**Comment by alexmerlin** [comment]
Fixed in [this commit](https://github.com/dotkernel/development/commit/6eff6796e6efd684d342016dfc861be8fcecdc21#diff-5fbd1cc514203da6c6ef76aff479e5725e32fc9c67da21cb13af3738e86c6f16)
