### ISSUE TITLE
npm install veraious versions

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#16]
1. make an ansible recipe npm for versions 12, 14, 16, 18 
3.  instructions how to swithc from one version to another 

https://blog.adnanhalilovic.com/2022/07/25/how-to-install-node-on-almalinux-9/

**Comment by arhimede** [comment]
switch nodejs versions 

`sudo yum remove -y nodejs
curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
sudo yum install -y nodejs`

**Comment by alexmerlin** [comment]
Fixed in #17
