### ISSUE TITLE
postman issue 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#21]
not working the localhost WSL

**Comment by arhimede** [comment]
127.0.0.1       localhost
	::1             localhost
	
	::1 the.zone

**Comment by alexmerlin** [comment]
There is no solution that works for all. For some, it works with `127.0.0.1`, for others, it works with `localhost`.
The real solution could be some Windows configuration - will look into this later when I have some time to dig.

**Comment by alexmerlin** [comment]
@arhimede @bidi47 @MarioRadu:
please test if using [this method](https://github.com/dotkernel/development/pull/30#issue-1972137408) you can access your copy of DotKernel API from both Postman and browser.

**Comment by arhimede** [comment]
@OnitaAndrei pelase test and confirm

**Comment by OnitaAndrei** [comment]
@alexmerlin I tested and it works on both

**Comment by alexmerlin** [comment]
Before merging this, it should be further tested by the devs for whom it only worked on either postman/browser.

**Comment by cPintiuta** [comment]
@alexmerlin tested on both Almalinux9 and Ubuntu
