### ISSUE TITLE
install mariadb 10.11 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#23]
https://github.com/dotkernel/development/blob/main/wsl/os/almalinux9/roles/mariadb/tasks/main.yml

Let's switch to 10.11 because of UUID data type 

Also we need instruction how to upgrade

**Comment by alexmerlin** [comment]
Upgrading from MariaDB **10.6** to **10.11:**
- Using your terminal, access your instance of AlmaLinux9
- Point MariaDB's repo file to version 10.11:
`sudo sed -i 's/10.6/10.11/' /etc/yum.repos.d/MariaDB.repo`
- Stop MariaDB 10.6:
`sudo systemctl stop mariadb`
- Uninstall MariaDB 10.6:
`sudo dnf remove MariaDB-server -y`
- Install MariaDB 10.11:
`sudo dnf install MariaDB-server -y`
- Start MariaDB 10.11:
`sudo systemctl start mariadb`

**Comment by alexmerlin** [comment]
Fixed in #24
