### ISSUE TITLE
missing mariadb.repo file

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#25]
is missing

**Comment by alexmerlin** [comment]
Missing where? From the repo or from the file system after installation?
In the repo, it is found [here](https://github.com/dotkernel/development/blob/main/wsl/os/almalinux9/roles/mariadb/templates/MariaDB.repo.j2).

**Comment by arhimede** [comment]
Missing from file system

**Comment by alexmerlin** [comment]
Just re-tested the installation process from start to finish and `MariaDB.repo` has been created under `/etc/yum.repos.d/`.
I need more info on the issue:
- was your copy of dotkernel/development up-to-date when you encountered this issue?
- did Ansible throw any error during the installation process?

**Comment by alexmerlin** [comment]
New installations seem to work fine; if we don't have enough details to reproduce this scenario, I guess we can close this issue.
We can repopen it later if it happens again.
