### ISSUE TITLE
Upgrade Mariadb to 11.4 LTS

### ISSUE THREAD

**Issue by arhimede** [dotkernel/development#40]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Let's upgrade the initial ansible recipe to install mariadb 11.4
and a small recipe for upgrade from 10.11 to 11.4

**Comment by arhimede** [comment]
**Manual upgrade instructions**

1. edit the /etc/yum.repos.d/Mariadb.repo and replace the string _10.11_ with _11.4_
2. `sudo dnf remove MariaDB-server -y`
3. `sudo dnf clean all`
4. `sudo dnf install MariaDB-server -y`
5. `sudo dnf install MariaDB-server -y`
6. `mariadb-upgrade -uroot -p`
7. `sudo  systemctl restart mariadb`

**Comment by alexmerlin** [comment]
Fixed in #41
