### ISSUE TITLE
WSL: Create Ansible playbook for AlmaLinux 8

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/development#8]

**Comment by arhimede** [comment]
Systemd support is now available in WSL!

[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/](url)

**Comment by arhimede** [comment]
install directly PHP 8.1

**Comment by arhimede** [comment]
we can drop this one , as in 1 year Almalinux 8 will be out of support 
@alexmerlin
