### ISSUE TITLE
WSL: Create Ansible playbook for AlmaLinux 9

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/development#9]

**Comment by arhimede** [comment]
Systemd support is now available in WSL!

[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/](url)

**Comment by arhimede** [comment]
install directly PHP 8.1

**Comment by arhimede** [comment]
Instead of Mysql, please install mariadb 10.6 
@alexmerlin

**Comment by alexmerlin** [comment]
AlmaLinux9 installation [here](https://github.com/dotkernel/development/tree/main/wsl/os/almalinux9)
